config/routes.rb
Jackson::Application.routes.draw do

  get '/sign-in',   to: 'sessions#new',      as: 'sign_in'
  get '/sign-out',  to: 'sessions#destroy',  as: 'sign_out'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]

  get "/profile", to: redirect("/profile/edit"), as: :profile
  get "/profile/edit", to: "profiles#edit", as: :edit_profile
  patch "/profile", to: "profiles#update", as: :update_profile

  resources :events do
    resources :responses, only: [:index, :create, :update, :destroy ]
  end

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  get '/home', to: 'base#home', as: 'home'

  root to: 'base#home'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_authentication

  def index
    page_title "Your Events"

    @events = current_user.events
    @created_events = current_user.created_events
    @upcoming_events = @events.upcoming | @created_events.upcoming
    @past_events = @events.past | @created_events.past
  end

end

app/views/dashboard/index.html.haml
.row
  - cache [ "v1", current_user, @events, @upcoming_events ] do
    .col-md-9
      %h3 My Upcoming Events
      - if @upcoming_events.any?
        = render @upcoming_events.sort_by(&:starts_at)
      - else
        .well{ style: "text-align: center" }
          %h1
            .icon-calendar
          %h3 You don't have any upcoming events.
          %p
            = link_to "Create an event", new_event_path
            yourself, or, if you're looking for something to do,
            check out #{ link_to "Ruby FTW", "http://rubyftw.org" }.

      -# - if @past_events.any?
        .page-header
          %h3 Past Events
        = render @past_events.sort_by(&:starts_at).reverse

  .col-md-3
    %h4 Stuff you might want to do

    %ul.nav.nav-stacked.nav-pills
      %li= link_to "Create an Event", new_event_path
      %li= link_to "My Past Events", "#"