config/routes.rb
Jackson::Application.routes.draw do

  get '/sign-in',   to: 'sessions#new',      as: 'sign_in'
  get '/sign-out',  to: 'sessions#destroy',  as: 'sign_out'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]

  get "/profile", to: redirect("/profile/edit"), as: :profile
  get "/profile/edit", to: "profiles#edit", as: :edit_profile
  patch "/profile", to: "profiles#update", as: :update_profile

  resources :events do
    resources :responses, only: [:index, :create, :update, :destroy ]
  end

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  get '/home', to: 'base#home', as: 'home'

  root to: 'base#home'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_authentication

  def edit
    page_title "Edit Profile"

    @user = current_user
    @user.update_column(:profile_complete, true)
  end

  def update
    @user = current_user
    @user.update_attributes(profile_params)

    redirect_to session.delete(:return_path).presence || dashboard_path
  end


  protected

  def profile_params
    params.require(:user).permit(:full_name, :email)
  end
end

app/views/profiles/edit.html.haml
.page-header
  %h1 Update your profile

= form_for @user, url: profile_path(@user) do |f|

  .form-group
    = f.label :full_name
    = f.text_field :full_name, class: "form-control"

  .form-group
    = f.label :email, "Email address"
    = f.text_field :email, class: "form-control"
    .help-block
      Your email is used to display a #{ link_to "Gravatar", "http://gravatar.com" } and to send a
      reminder on the morning of the event. We won't sell or otherwise abuse your email address.
      Promise.

  = f.submit "Update Profile", class: "btn btn-primary"

-# %hr

-# %h3 Connect your other accounts

-# .btn-group
  = link_to auth_path(:github), class: "btn btn-default #{ "disabled" if current_user.provider?("github") }" do
    %span.icon-githubj
    GitHub
  = link_to auth_path(:twitter), class: "btn btn-info #{ "disabled" if current_user.provider?("twitter") }" do
    %span.icon-twitter-bird
    Twitter
  = link_to auth_path(:facebook), class: "btn btn-primary #{ "disabled" if current_user.provider?("facebook") }" do
    %span.icon-facebook
    Facebook
  = link_to auth_path(:gplus), class: "btn btn-danger #{ "disabled" if current_user.provider?("gplus") }" do
    %span.icon-gplus
    Google+