config/routes.rb
Jackson::Application.routes.draw do

  get '/sign-in',   to: 'sessions#new',      as: 'sign_in'
  get '/sign-out',  to: 'sessions#destroy',  as: 'sign_out'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]

  get "/profile", to: redirect("/profile/edit"), as: :profile
  get "/profile/edit", to: "profiles#edit", as: :edit_profile
  patch "/profile", to: "profiles#update", as: :update_profile

  resources :events do
    resources :responses, only: [:index, :create, :update, :destroy ]
  end

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  get '/home', to: 'base#home', as: 'home'

  root to: 'base#home'
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :require_signed_out

  def home
    page_title "Home"
  end

  private

  def require_signed_out
    redirect_to dashboard_path if current_user?
  end
end

app/views/base/home.html.haml
.jumbotron
  %h1
    %span.icon-thumbs-up
    Jackson is there.
  %p And you know he'll be there because he RSVPed. And he's bringing friends.
  -# .visible-xs-block.visible-sm-block
    = link_to sign_in_path, class: "btn btn-success btn-lg btn-block" do
      Sign in
  -# .btn-group.hidden-xs.hidden-sm
    = link_to sign_in_path, class: "btn btn-success btn-lg", "data-no-turbolink" => true do
      Sign in
    = link_to auth_path(:github), class: "btn btn-default btn-lg", "data-no-turbolink" => true do
      %span.icon-github
      GitHub
    = link_to auth_path(:twitter), class: "btn btn-info btn-lg", "data-no-turbolink" => true do
      %span.icon-twitter-bird
      Twitter
    = link_to auth_path(:facebook), class: "btn btn-primary btn-lg", "data-no-turbolink" => true do
      %span.icon-facebook
      Facebook
    = link_to auth_path(:gplus), class: "btn btn-danger btn-lg", "data-no-turbolink" => true do
      %span.icon-gplus
      Google+

.row
  .col-md-4
    %h3
      %span.icon-beaker
      Recipe for success!
    %p Social sign-in bingo. Sign in with your GitHub, Twitter, Facebook, or Google+ account.

  .col-md-4
    %h3
      %span.icon-megaphone
      Tell all your friends
    %p
      Your guests can bring friends. Just adjust the number of additional guests when you RSVP.
      You can also leave a comment for everyone to see!

  .col-md-4
    %h3
      %span.icon-lightbulb
      Reminder Email
    %p Get a reminder email on the day of your event. So you don't forget!