config/routes.rb
Jackson::Application.routes.draw do

  get '/sign-in',   to: 'sessions#new',      as: 'sign_in'
  get '/sign-out',  to: 'sessions#destroy',  as: 'sign_out'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]

  get "/profile", to: redirect("/profile/edit"), as: :profile
  get "/profile/edit", to: "profiles#edit", as: :edit_profile
  patch "/profile", to: "profiles#update", as: :update_profile

  resources :events do
    resources :responses, only: [:index, :create, :update, :destroy ]
  end

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  get '/home', to: 'base#home', as: 'home'

  root to: 'base#home'
end

app/views/shared/_current_user.html.haml
- if current_user?
  %li
    = link_to edit_profile_path do
      = image_tag current_user.avatar, width: 20,
        style: "position: relative; top: -1px; border-radius: 20px;"
      &nbsp;
      = current_user.full_name
  %li= link_to "Sign Out", sign_out_path
- else
  %li.dropdown
    %a.dropdown-toggle{ href: "#", data: { toggle: "dropdown" } }
      Sign In
      %b.caret
    %ul.dropdown-menu
      %li
        = link_to auth_path(:github) do
          %span.fa.fa-github
          Sign in with GitHub
      %li
        = link_to auth_path(:twitter) do
          %span.fa.fa-twitter
          Sign in with Twitter
      %li
        = link_to auth_path(:facebook) do
          %span.fa.fa-facebook
          Sign in with Facebook
      %li
        = link_to auth_path(:gplus) do
          %span.fa.fa-google-plus
          Sign in with Google+

app/views/shared/_header.html.haml
.navbar.navbar-default#navigation{ style: "border-radius: 0", "data-turbolinks-permanent" => "true" }
  .container
    .navbar-header
      = link_to root_path, class: "navbar-brand" do
        %span.icon-thumbs-up
        Jackson
      %button.navbar-toggle{ data: { toggle: "collapse", target: "#user_nav" } }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    .collapse.navbar-collapse#user_nav
      %ul.nav.navbar-nav.navbar-right
        = render "shared/current_user"